### ISSUE TITLE
Error `equality without matching types`

### ISSUE THREAD

**Issue by mgudemann** [diffblue/cbmc#162]
For the following program

```
public class NullPointer5
{
  void f()
  {
    Object o = new Object();
    if(null == o)
      assert false;
    assert true;
  }
  void g()
  {
    Object o = new Object();
    if(o == null)
      assert false;
    assert true;
  }
}
```

the result of checking `--function NullPointer5.g` is ok, while `--function NullPointer.f` fails with the above error.

The same error is triggered with `--function Inheritance3.f` in

```
class Inheritance3
{
  class A
  {
  }
  class B extends A
  {
  }
  void f()
  {
    A a = new A();
    B b = new B();
    if(a == b)
      assert false;
    assert true;
  }
}
```

**Comment by smowton** [comment]
Addressed in https://github.com/smowton/cbmc/commit/5787def334f79c577c84e2783f5363176d6e53fb

This stemmed from indirecting via a local variable, which was given an inconsistent type (sometimes A* and sometimes void*). This commit simply treats pointer-typed locals as void* under all circumstances, since the same variable can be used with different types in different places in any case. The void* pointers are downcast to their proper types when needed (e.g. at method call sites, field accesses).

**Comment by smowton** [comment]
Fixed in Cristina's test_gen branch
