### ISSUE TITLE
CBMC hangs on multiplication and division

### ISSUE THREAD

**Issue by polgreen** [diffblue/cbmc#1649]
CBMC gets stuck verifying this simple multiplication function:
~~~
unsigned int multi(const unsigned int a, const unsigned int b)
{
  return a*b;
}

int main(void)
{
  const unsigned int lhs, rhs;
  __CPROVER_assert(multi(lhs,rhs)==(lhs*rhs), "");
  return 0;
}
~~~
It hangs on a SAT formula of size 3177 variables, 16794 clauses.

Any insights as to why, or any better ways of writing this function? @martin-cs ?

**Comment by martin-cs** [comment]
What's Happening
-----------------------

"Difficulty" in the SAT formulae comes from particular operators (*, /, % and variable shifts) and from the way they are combined.  You have created a small but very hard formula.  There are others that demonstrate similar behaviour ( for example, associativity, see https://github.com/diffblue/cbmc/pull/63 ).

What You Can Do
-----------------------
1. Rewrite so that the "constant" propagation and simplification pass allows this equality to be syntactically resolved (--show-vcc will confirm this once you've got it right!)

2. Try out @tautschnig 's "propagate all the things" during symex patch, which should handle this.

3. Try out an SMT solver which does equality rewriting, such as CVC4.

4. Help me improve the equality handling in the CPROVER back-end.

5. Help resurrect the work on better multiplier encodings that @jasigal was helping me with.

HTH
