### ISSUE TITLE
Introduce a java_source_locationt to contain Java specific source location information

### ISSUE THREAD

**Issue by thk123** [diffblue/cbmc#1824]
Currently the language agnostic contains the Java bytecode index and (as of #1812) the `remove_virtual_call` flag. These should be pulled into a `java_bytecode_source_locationt`.

**Comment by thomasspriggs** [comment]
Yes, separating out a Java specific variation of `source_locationt`, sounds like it would be a worthwhile refactor. However, given how long this issue has been open it doesn't seem to be a priority for anyone to actually get done. Therefore I am going to close out this issue, rather than leaving it open indefinitely.
