### ISSUE TITLE
What should goto-instrument's --points-to analysis do?

### ISSUE THREAD

**Issue by martin-cs** [diffblue/cbmc#222]
As far as I can see, it doesn't do anything at the moment.  Seeing as I'm looking at pointer analysis for abstract interpretation it seemed a good time to ask what, if anything, it should be doing.

**Comment by thomasspriggs** [comment]
`goto-instrument` doesn't seem to have a `--points-to` argument any more. I am assuming its been either renamed or removed in the 4 years since you asked this question. I am also going to close out this issue as part of a clean-up effort. If you still have questions about an equivalent current argument/analysis then feel free to re-open.

**Comment by martin-cs** [comment]
I think I removed the option after it was clear that it wasn't implemented and wasn't needed.  I can't find the commit but, from my point of view, this is done.

**Comment by thomasspriggs** [comment]
> I think I removed the option after it was clear that it wasn't implemented and wasn't needed. I can't find the commit but, from my point of view, this is done.

:+1:
