### ISSUE TITLE
Pointers to struct members

### ISSUE THREAD

**Issue by kroening** [diffblue/cbmc#235]
Added test regression/cbmc/struct9 with 47170bd.

**Comment by smowton** [comment]
Problem is that in the double-deref (`*(inner->GUARDp)`) the first deref returns a byte-extract operation (since the `inner` aliases an `outer`), and then the second can't get a points-to set off of `byte_extract` and so returns `invalid-object`

**Comment by smowton** [comment]
Candidate fix in https://github.com/smowton/cbmc/tree/symex_deref_clean_struct_member, which in the case of a constant pointer offset returns an arbitrarily nested series of member-of and index-of expressions if possible, rather than resorting to byte-extract right away. That fixes the testcase posted.

It doesn't however fix the general case where a real reinterpret case has happened, so byte-extract is perhaps the only reasonable way to express what has happened, and then further pointers are followed. At present `invalid_object` is offered up as a dangling nondet, hence the spurious counterexample, but I can't immediately think how to compile a program that derefs off a reinterpret except by generating a value set containing every object.

**Comment by kroening** [comment]
May I have a pull request for this, please?

**Comment by smowton** [comment]
Submitted #283

**Comment by kroening** [comment]
Merged.
