### ISSUE TITLE
SVCOMP-benchmark incorrect (memcpy src/dst overlap)

### ISSUE THREAD

**Issue by xbauch** [diffblue/cbmc#3428]
Reporting on one SVCOMP benchmarks that were working in previous versions (5.8) but CBMC give incorrect result now. The benchmark code is here:

https://github.com/sosy-lab/sv-benchmarks/blob/master/c/ntdrivers/floppy_true-unreach-call_true-valid-memsafety.i.cil.c

CBMC version: 5.10
Operating system: 64-bit linux
Exact command line resulting in the issue: ./cbmc --graphml-witness witness.graphml --32 --propertyfile ../sv-benchmarks/c/ReachSafety.prp ../sv-benchmarks/c/ntdrivers/floppy_true-unreach-call_true-valid-memsafety.i.cil.c
What behaviour did you expect:

VERIFICATION SUCCESSFUL
EC=42
UNKNOWN

What happened instead:

Violated property:
  file ../sv-benchmarks/c/ntdrivers/floppy_true-unreach-call_true-valid-memsafety.i.cil.c line 3549 function FloppyStartDevice
  memcpy src/dst overlap
  POINTER_OBJECT((void *)nextIrpSp) != POINTER_OBJECT((const void *)irpSp___0)

VERIFICATION FAILED
EC=10
FALSE

**Comment by xbauch** [comment]
Also occurs here: https://github.com/sosy-lab/sv-benchmarks/blob/master/c/ntdrivers/diskperf_true-unreach-call.i.cil.c

**Comment by xbauch** [comment]
Also occurs here: https://github.com/sosy-lab/sv-benchmarks/blob/master/c/ntdrivers/floppy2_true-unreach-call_true-termination.i.cil.c

**Comment by xbauch** [comment]
This benchmark is related: https://github.com/sosy-lab/sv-benchmarks/blob/master/c/ntdrivers/cdaudio_true-unreach-call.i.cil.c

the currect CBMC reports the same violation as above but CBMC 5.8 returned:

VERIFICATION SUCCESSFUL
EC=0
TRUE

**Comment by tautschnig** [comment]
Is all this still the case after https://github.com/sosy-lab/sv-benchmarks/pull/673?

**Comment by tautschnig** [comment]
In fact quite possibly so, the PR didn't touch the old NT drivers. @karkhaz would you know about the benchmarks @xbauch is mentioning above?

**Comment by karkhaz** [comment]
https://github.com/sosy-lab/sv-benchmarks/pull/673 did not touch the NT drivers, but I actually fixed those in the earlier PR https://github.com/sosy-lab/sv-benchmarks/pull/597. We believe that it is the benchmark that is incorrect, not CBMC; CBMC correctly reports that the memory regions overlap, so I fixed those benchmarks in those two pull requests. @xbauch please pull the latest sv-benchmarks (no earlier than a few hours ago, since that's when 673 was merged) and try again?

That there may still be some benchmarks where CBMC reports that the memory regions overlap, which I haven't fixed yet. In general, I believe that these would all be correct bug reports, and it is the benchmark that should be amended.

**Comment by xbauch** [comment]
The latest benchmark results no longer show these as incorrect, I guess we should close this issue and concentrate on the actually incorrect ones.
