### ISSUE TITLE
SMT2 back-end float to bit-vector conversion of multiply hangs

### ISSUE THREAD

**Issue by martin-cs** [diffblue/cbmc#344]
Non-urgent, documented for completeness and so we don't forget rather than for an urgent fix.

$ cat path.c
#include <assert.h>

int main (void) {
        float f;

        assert(f * f > 28);

        return 0;
}

$ cbmc path.c --smt2 --outfile -

Works with --fpa as well.

**Comment by mbeckersys** [comment]
More information on this: It's not (only) the multiplication. The same behavior occurs with the following program:

```
void main() {
    float x;
    x = 3.5 - x;
    assert ( x < 3.2);
}
```
Debugger shows that in both cases the `irep::hash` function is stuck (busy calling itself) when `map.find(expr)` is called in `smt2_convt::collect_bindings`.

**Comment by tautschnig** [comment]
That's a very interesting insight. Would you mind trying to set `#define HASH_CODE` in `src/util/irep.h`? That seems to make it terminate very quickly for me.

**Comment by mbeckersys** [comment]
Incidently, we had the same idea moments ago. Yes, that helps.

Apparently, with `HASH_CODE` defined, the cycle is broken and everything works again. Besides higher memory consumption, does this have other side effects?

**Comment by tautschnig** [comment]
> [...] does this have other side effects?

None other than considerable performance improvement.

**Comment by rmetta** [comment]
Further, if one uses -fpa, the resulting 'Floating Point' encoding is not supported by yices (which is our current choice, as yices is outperforming both z3 and MathSat on our applications). The HASH_CODE fix is definitely better, both for performance and for the choice of running yices.

**Comment by tautschnig** [comment]
Mainly for @kroening and @martin-cs: The example that @mbeckersys posted yields an expression that, when explored to depth 43, has 848557880 nodes. Either there genuinely is a loop in the data structure, or it's simply extremely large.

**Comment by rmetta** [comment]
A point to note: this very example is solved by cbmc+z3 within a second,
when cbmc is invoked with -fpa.




On 24-Feb-2018 00:01, "Michael Tautschnig" <notifications@github.com> wrote:

Mainly for @kroening <https://github.com/kroening> and @martin-cs
<https://github.com/martin-cs>: The example that @mbeckersys
<https://github.com/mbeckersys> posted yields an expression that, when
explored to depth 43, has 848557880 nodes. Either there genuinely is a loop
in the data structure, or it's simply extremely large.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/diffblue/cbmc/issues/344#issuecomment-368097746>, or mute
the thread

**Comment by kroening** [comment]
The program with the multiplication is now solved in <1s.
