### ISSUE TITLE
CBMC 5.10 type checking error - implicit function declaration

### ISSUE THREAD

**Issue by avritichauhan** [diffblue/cbmc#4275]
cbmc 5.8 (windows), runs fine and gives expected output "Verification Failed" (without any errors) on the following test case.  However, cbmc 5.10 (windows version) gives a type checking error - "implicit function decalration".  Also, compilation using gcc, does not gives any error.

![image](https://user-images.githubusercontent.com/24314631/53324252-55962100-3906-11e9-8586-178ffb67427e.png)

Test case with 2 c files:
**test.c**
void main()
{
	foo();
	assert(0);
}
**test1.c**
extern void foo();
void foo()
{
int a=0;
}

CBMC version: CBMC version 5.10 (cbmc-5.10) 32-bit i386 windows
Operating system: Windows 7 (64 bit OS)
Exact command line resulting in the issue: cbmc.exe --function main test.c test1.c
What behaviour did you expect: Verification Failed (without any errors)
What happened instead: Type checking error

Please give suggestions to solve this issue.

**Comment by tautschnig** [comment]
This is expected behaviour: the missing declaration of `foo` in `test.c` results in a default type for `foo` being assumed, which turns out not be consistent with the definition in `test1.c`. GCC (or, more specifically, ld) does not perform link-time type checking, and thus cannot detect this error.
