### ISSUE TITLE
Replace custom json parser with library

### ISSUE THREAD

**Issue by NathanJPhillips** [diffblue/cbmc#456]
There is a custom json parser in util/json.h & util/json.cpp where plenty of tried-and-tested and more complete json libraries exist out there. I have personally made use of the json parser in cpprestsdk available here: https://github.com/Microsoft/cpprestsdk/blob/master/Release/include/cpprest/json.h

**Comment by trtikm** [comment]
We already made a dependency to boost., where already is a complete JSON parser.

**Comment by kroening** [comment]
CBMC is used by outsiders, and we want to enable and support this. Experience suggests to be very conservative with external dependencies, as build is a serious barrier for many. We already got problems with libzip/zlib.

**Comment by thomasspriggs** [comment]
As nice as it would be from a maintenance point of view to be using a standard library, it would add to the difficultly of building CBMC. We also don't have time allocated to do the rewriting which would be required to use a new library instead of the existing interface. I am therefore closing this out as part of a open issues clean-up effort and due to the aforementioned reasons.
