### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by ghost** [diffblue/cbmc#5099]
I'm trying to use CBMC to find such an inputs for a function so that it will return, say, "true" or 1.
Like this:

    bool f(char *a, char *b)
    {
        return atoi(a)==123 && atoi(b)==456;
    };

What should I do?

**Comment by martin-cs** [comment]
So there are a few things you will need.  First off you will need an assertion, because you need something to check -- you need to tell the tool that you want f to return 1.  Secondly you will need some kind of set up of the calling context.  If you tell cbmc to start somewhere other than main (using `--function f00`) then it will make the function inputs non-deterministic.  This is easy for basic types but in the case of pointers it is much harder.  Does it point to something initialised?  If so, how large is the object?  Can they alias the same object?  For pointers you often need to build a calling context which gives at least the shape of the memory that is pointed to.

I think this may do what you want:

```
#include <assert.h>

int f(char *a, char *b)
{
  return atoi(a)==123 && atoi(b)==456;
}

#define LENGTH 10

int main (int argc, char **argv) {
  char buffer1[LENGTH];   // Uninitialised things are non-det
  char buffer2[LENGTH];

  buffer1[LENGTH - 1] = '\0'; // Let's work with null terminated strings
  buffer2[LENGTH - 1] = '\0'; // Let's work with null terminated strings

  int res = f(buffer1, buffer2);

  assert(!res);  // Will generate case when res is true

  return 0;
}
```

**Comment by ghost** [comment]
Thanks, I tried that, but couldn't find correct cbmc command options...

**Comment by martin-cs** [comment]
Which options did you use?  You might want `--trace` if you want the execution trace that causes the assertion to fail.

**Comment by ghost** [comment]
Thanks, let me try...

**Comment by martin-cs** [comment]
@DennisYurichev : any joy?

**Comment by lwerdna** [comment]
@martin-cs Yes, he was successful: https://yurichev.com/news/20200416_CRC64/

It has worked for me too, thank you for your support.

**Comment by martin-cs** [comment]
Great to see the end result!  Thanks for following up.
