### ISSUE TITLE
__CPROVER_assume does not work for global variables

### ISSUE THREAD

**Issue by dlohar** [diffblue/cbmc#5120]
CBMC version: 5.12
Operating system: Debian
Exact command line resulting in the issue: cbmc test.c
What behaviour did you expect: assertion violation
What happened instead: verification successful

Following is the test code. 
```
#include<stdio.h>
#include<stdlib.h>
double mass;
int main() {
  __CPROVER_assume((mass >= 5.0) && (mass <= 50.0));
  double test = 0.0;
  __CPROVER_assert(test != 0.0, "error");
  return 0;
}
```
If I keep the declaration of mass inside main, the assertion fails, but if I make it a global variable the verification becomes successful.

**Comment by polgreen** [comment]
I believe this is because global variables in C are initialised as 0 and local variables are not. If you declare mass as a global, it is initialised to 0 and then the assume blocks all program paths. 

From the manual: http://www.cprover.org/cprover-manual/modeling/assumptions/
"You must ensure that the condition given as an assumption is actually satisfiable by some nondeterministic choice, otherwise the model checking step will pass vacuously."

**Comment by dlohar** [comment]
Then how do I assume a range for the global variable? I tried adding an assumption after the global declaration, but that did not work.

**Comment by polgreen** [comment]
If you need to assume the global takes some value in a range, you could initialise the global by assigning to it with a function with no body, which makes it a nondeterministic value, like this:

~~~
double mass=nondet();

int main() {
  __CPROVER_assume((mass >= 5.0) && (mass <= 50.0));
  double test = 0.0;
  __CPROVER_assert(test != 0.0, "error");
  return 0;
}
~~~

An assumption btw won't override the behaviour of the C program, it only restricts it. That's why it passes vacuously if you put that assumption on an uninitialised global. In C, the uninitialised global is equal to 0 so it was equivalent to doing this:

~~~
double mass=0;
__CPROVER_assume(mass>=5 && mass<=50);
~~~
And there are no paths that satisfy mass=0 & mass >=5 && mass<=50.

**Comment by dlohar** [comment]
This works. Thanks.
