### ISSUE TITLE
incorrect behaviour on cosine/sine

### ISSUE THREAD

**Issue by polgreen** [diffblue/cbmc#5422]
CBMC gives wrong answers to cosine? I don't know if CBMC supports cosine/sin, but I infer from issue https://github.com/diffblue/cbmc/issues/3438, and the libraries in /src/ansi-c that it is intended to support it to some extent?

CBMC version: 5.12 (cbmc-5.12.3-4-g0c08382c2)
Operating system: MacOS
Exact command line resulting in the issue: cbmc cosine.c

cosine.c is:
~~~
#include <math.h>

void main()
{
    double value=0.5;
    double result = cos(0.5);
    assert(result > 0.5);
}
~~~
What behaviour did you expect: the assertion to pass, i.e., cos(0.5)>0.5

This seems reasonable, when I compile and run the following program it prints "The Cosine of 0.500000 is 0.877583"
~~~
#include <stdio.h>
void main()
{
    double value=0.5;
    double result = cos(0.5);
    printf("The Cosine of %f is %f\n", value, result);
}
~~~

What happened instead: the assertion failed and the trace reports that result=2.386669e-153. It doesn't seem to matter what i place the bounds as in the assertion (provided if <=1, >=-1), it will always fail so I don't think this is anything to do with floating point errors.

**Comment by peterschrammel** [comment]
CBMC does not support exact verification of trig functions out of the box. It only has a very rough, over-approximating model for them: https://github.com/diffblue/cbmc/blob/develop/src/ansi-c/library/math.c#L413
Bit-precise verification of trig functions is tricky because the exact behaviour depends on the library that you use. You'd have to pass to CBMC the implementation of the maths library that your application uses or build a model that is precise enough for your needs.

**Comment by polgreen** [comment]
Ok, so it couldn't ever have solved the problem referenced in https://github.com/diffblue/cbmc/issues/3438, even if the problem had been correctly specified because all it can do is assume that the return value is within the bounds -1 and 1?

**Comment by martin-cs** [comment]
@polgreen if you need exacttrig things let me know as it has been something I have been working on and will hopefully be getting code working early next year?
