### ISSUE TITLE
Maven / Gradle plugin for jbmc

### ISSUE THREAD

**Issue by sbelodon** [diffblue/cbmc#5597]
Hello!

Why jbmc isn't available as maven or gradle plugin? Maybe some developers wants to check their code and plugin is the easiest way to do this.

CBMC version:
Operating system:
Exact command line resulting in the issue:
What behaviour did you expect:
What happened instead:

**Comment by martin-cs** [comment]
Ummm... because no-one has written one yet?  Development in CBMC tends to be driven by what the developers / their customers / sponsors want rather than there being any centralised plan.  There have been IDE plug-ins in the past but they have required a non-trivial amount of maintenance and after a while, no one was willing to maintain them.

Diffblue sells a number of products that include things built on JBMC and I think have integration into at least Gradle.  Maybe @peterschrammel could say more about them?

**Comment by hannes-steffenhagen-diffblue** [comment]
Hello, a Maven or Gradle plugin with JBMC is currently not planned. That doesn't mean it wouldn't be useful, on our end we just don't have the capacity for it. We'd certainly love a PR adding something like this.
