### ISSUE TITLE
segfault on some java class 

### ISSUE THREAD

**Issue by mgudemann** [diffblue/cbmc#561]
there's a SIGSEV on some Java classes, bisecting points to merge commit cbmc@509cf25338f9ff8d25bd7262fd96296be378a350 as begin the first bad one, both parent commits do not segfault

**Comment by smowton** [comment]
@forejtv I don't have rights to assign here, could you assign me please?

**Comment by smowton** [comment]
The immediate parent of that commit only doesn't segfault because it throws due to a different bug. The cause is https://github.com/diffblue/cbmc/commit/50d161cbb0c81eceb3354d923d3d3faae390a46d

**Comment by smowton** [comment]
At that point (when initialising a pointer-typed field), `class_identifier` gives the type of the structure whose field we're currently initialising (so if we're initialising a `B*` that's part of a `class A`, `class_identifier` is `A`). It only becomes `B` once we've allocated a B and deref'd it (the expr.id()==ID_struct case below).

The given test case has mutually recursive types (`class A { B* b; }` and `class B { A* a; }`), and since the recursion set has been effectively disabled it tries to initialise an infinite series of objects.

Since the problem commit belonged to @mgudemann and I don't know what the check was trying to achieve, I'll assign this back to him (@peterschrammel would you mind doing that?)

**Comment by tautschnig** [comment]
Assignments done; is there a test case that can be used as regression test for any PR fixing this issue?

**Comment by mgudemann** [comment]
I'll try to distill one from one of the classes that triggered this error.

**Comment by mgudemann** [comment]
done in #824
