### ISSUE TITLE
nondet_unsigned_char() has type 'int' instead of 'unsigned char'

### ISSUE THREAD

**Issue by adpaco-aws** [diffblue/cbmc#5643]
CBMC version: 5.17.0
Operating system: macOs 10.15
Exact command line resulting in the issue: `goto-cc` and `cbmc` with flags
```
cbmc   --unwind 1 --unwindset aws_cryptosdk_private_commitment_eq.0:5 --flush --object-bits 8  --malloc-may-fail --malloc-fail-null --bounds-check --conversion-check --div-by-zero-check --float-overflow-check --nan-check --pointer-check --pointer-overflow-check --pointer-primitive-check --signed-overflow-check --undefined-shift-check --unsigned-overflow-check --unwinding-assertions --trace
```
on the following code:

```
void write_unconstrained_data(unsigned char *out, size_t len) {
    if (len > 0) {
        size_t index;
        __CPROVER_assume(index < len);
        out[index] = nondet_unsigned_char();
    }
}
```

What behaviour did you expect: No errors.
What happened instead: Get error "arithmetic overflow on signed to unsigned type conversion in (unsigned char)return_value_nondet_unsigned_char"

`nondet_unsigned_char()` appears to have type `int` instead of `unsigned char`. This may also be the case for similar functions.

**Comment by tautschnig** [comment]
@adpaco-aws Is this literally the complete code? If so: `nondet_unsigned_char` isn't declared, which you will have gotten a warning about. For an undeclared function, C assumes `int` to be the return type.

**Comment by adpaco-aws** [comment]
No, the complete code is here: https://github.com/adpaco-aws/aws-encryption-sdk-c/tree/derive-nondet-char
After cloning recursively, go to `aws-encryption-sdk-c/verification/cbmc/proofs/derive_data_key` and run `make`.

In the warnings I do not see this function. We looked for its definition in the project but could not find it, so we assumed this was coming from CBMC.

**Comment by tautschnig** [comment]
Much like #5641, running `goto-cc` with `-Wall` (and perhaps: `-Werror`) would be really helpful here: you'd get a warning if directly running this C code past CBMC, but since `goto-cc` is part of the workflow, it's for `goto-cc` to report the problem.

> We looked for its definition in the project but could not find it, so we assumed this was coming from CBMC.

No, CBMC does not have anything pre-defined here. It's just that it will create a somewhat more efficient encoding when seeing a function named with prefix `nondet_` - but it doesn't have a magic way to figure out the type. So you will need to add a declaration

`unsigned char nondet_unsigned_char();`

before using the function.

**Comment by feliperodri** [comment]
This is no longer a problem for us anymore.
