### ISSUE TITLE
Should array sizes be signed or unsigned?

### ISSUE THREAD

**Issue by danielsn** [diffblue/cbmc#5819]
Currently, CBMC uses signed, but wouldn't unsigned make more sense? What does a negative array size mean?

**Comment by kroening** [comment]
The C standard isn't reasonably clear on that. C11 6.7.6.2 says "If they delimit an expression (which specifies the size of an array), the expression shall have an integer type. If the expression is a constant expression, it shall have a value greater than zero."

The second sentence implies that we can't simply cast to unsigned, since that would make the check meaningless.

If you are generating your own GOTO program, you can certainly use an unsigned type.

**Comment by hannes-steffenhagen-diffblue** [comment]
@danielsn Hello Daniel, does @kroening's comment answer your question? Are you ok with closing this?

**Comment by hannes-steffenhagen-diffblue** [comment]
@danielsn I'm closing this for now because it looks like @kroening's comment answers the question. If you think otherwise please let me know.
