### ISSUE TITLE
solving speedup proposition

### ISSUE THREAD

**Issue by sbelodon** [diffblue/cbmc#6050]
Hello!

I was thinking how to speedup generated CNF file solving and remember that there is ANF form https://en.wikipedia.org/wiki/Algebraic_normal_form
Theoretically it can be faster because ANF can be minimized faster (Needed to delete equal terms of ANF),
besides in some cases ANF may be smaller that CNF.

Is there a possibility to add ANF generation to CBMC? 
I know that there is no ANF solvers, but It can be developed even by me)

Some article describing solving:
https://www.academia.edu/36033079/Zhegalkin_Polynomials_SAT_Solver

Thanks!

**Comment by martin-cs** [comment]
A few thoughts...

1. Have a look at the AIG code `solvers/prop/aig`.  These work with And-Inverter-Graphs which is a popular form used by the hardware model checking folks and solvers like Bitwuzla.  They claim that it is a net improvement.  When I was working on this and using the AIGs to generate CNF I found that it took quite a bit of work to match the CNF we normally generate.  There are certainly things like the optimal full adder that seem to be difficult to match via AIGs.

2. Since then there have been a number of improvements in SAT preprocessing ( and inprocessing ) and it is now less clear whether the optimisations that AIGs enable are actually unique to them or whether they can be simulated.

3. One of the limits of AIGs is handling XORs.  @msoos has spent at least a decade working on integrating XOR reasoning into his SAT solver, https://github.com/msoos/cryptominisat and if you are interested in this area then you should definitely look at that.

4. Non-clausal SAT solvers are one of those "this really should work" ideas (GPU SAT solvers are another!) that many people have worked on over the last 25 years but never quite seem to work as well as we might think.  I spent quite some time trying and also, did not succeed.  I think there are a range of reasons why but ... that is probably more of a discussion than would fit in a github issue.

So, yes, there is potential here and by all means, have a go, you will learn loads and (hopefully) have a lot of fun.  But ... I wouldn't expect to deliver significant improvements over the latest SAT solvers with less than a PhD's worth of effort.  I hope I am wrong; I would love it if someone proved me wrong!

If your aim is to improve performance of CBMC then there a many (often less exciting) things that could be done and would deliver more immediate improvements.

**Comment by thomasspriggs** [comment]
I guess this could be done based on adding a new subclass of the `propt` class, if you wanted to experiment with this. The work currently being planned by cbmc developers within diffblue is currently more focused on improvements for cbmc's support for SMT solving, in an attempt to take better advantage of existing solvers. Please feel free to share your results with us if you do experiment with ANF.
