### ISSUE TITLE
Displaying SSA Conversion

### ISSUE THREAD

**Issue by luke-croak** [diffblue/cbmc#6245]
CBMC version: 5.28.0
Operating system: Ubuntu 20.04.2 LTS

I've found that I'm able to display the SSA conversion of a program by adding the option `--write-solver-stats-to`. However this has much more information than I'm wanting. Is there a simpler option for just displaying the SSA conversion done by CBMC? I'm trying to understand how CBMC converts to SSA (in particular where it places the phi nodes).

**Comment by martin-cs** [comment]
Have you tried `--show-vcc`?  That will give you the end result of the conversion.  Failing that, increasing the `--verbosity` level will give you a log of the SSA as it is working.  phi nodes are placed eagerly when control-flow paths merge.

**Comment by luke-croak** [comment]
Yep, `show-vcc` works!

I'm still confused by the phi nodes. From my understanding phi nodes are only inserted when there is a possibility of referring to different instances of the same variable due to an assignment that occurs along different paths. However, in CBMC (in some cases) it generates a phi node for a variable referenced in a guard and in other cases it does not. It seems to be that when the guard tests for equality (or inequality) it will generate a phi node for the relevant variable, otherwise it will not. Do you know why this behaviour occurs?

**Evidence of Unexpected Behaviour**
This behaviour can be seen in two examples. For the following program:
```
int nondet_int();
int main(){
    int a = nondet_int();
    int b = nondet_int();
    int test = 0;

    if (a == 2){
        if (b == 1){
            test = 1;
        }
    }
    __CPROVER_assert(test != 1, "postcondition");
}
```
If `cbmc --show-vcc example.c` is run it will result in phi nodes being generated after the guards (as would be expected if an assignment had occurred within the bounds of the guards):
```
{-24} goto_symex::\guard#1 ⇔ (main::1::a!0@1#2 = 2)
{-25} goto_symex::\guard#2 ⇔ (main::1::b!0@1#2 = 1)
{-26} main::1::test!0@1#3 = 1
{-27} main::1::test!0@1#4 = (goto_symex::\guard#1 ∧ ¬goto_symex::\guard#2 ? 0 : 1)
{-28} main::1::b!0@1#4 = (goto_symex::\guard#1 ∧ ¬goto_symex::\guard#2 ? main::1::b!0@1#2 : 1)
{-29} main::1::test!0@1#5 = (goto_symex::\guard#1 ? main::1::test!0@1#4 : 0)
{-30} main::1::b!0@1#5 = (goto_symex::\guard#1 ? main::1::b!0@1#4 : main::1::b!0@1#2)
{-31} main::1::a!0@1#4 = (goto_symex::\guard#1 ? 2 : main::1::a!0@1#2)
```

However for this program (where the equality tests changed to inequality):
```
int nondet_int();
int main(){
    int a = nondet_int();
    int b = nondet_int();
    int test = 0;

    if (a < 2){
        if (b > 1){
            test = 1;
        }
    }
    __CPROVER_assert(test != 1, "postcondition");
}
```
When `cbmc --show-vcc example2.c` is executed phi nodes are not generated for the variables `a` or `b`:
```
{-24} goto_symex::\guard#1 ⇔ ¬(main::1::a!0@1#2 ≥ 2)
{-25} goto_symex::\guard#2 ⇔ (main::1::b!0@1#2 ≥ 2)
{-26} main::1::test!0@1#3 = 1
{-27} main::1::test!0@1#4 = (goto_symex::\guard#1 ∧ ¬goto_symex::\guard#2 ? 0 : 1)
{-28} main::1::test!0@1#5 = (goto_symex::\guard#1 ? main::1::test!0@1#4 : 0)
```

**Comment by martin-cs** [comment]
I think what you are seeing is the effect of constant propagation that is triggered by the conditions.  When symex reaches the `if(a == 2)` it will (eventually) trigger this code:

https://github.com/diffblue/cbmc/blob/9e3edf7d545e613ba948f8d9e51d9b4423594307/src/goto-symex/goto_state.cpp#L86

which recognises that the condition allows assigning `a` to a constant.  It does this and so generates a new SSA name.  When the paths merge again, the names are different on each path, so a phi node is added to bring them back together.  This should happen with `!=` but won't happen with `a < 2` because that doesn't give a constant that it can be assigned to.

One way to check this is to insert:

```
int counter;
for (int i = 0; i < a; ++i) { counter += i; }
```

in the branch.  If `a` has been constant propagated to `2` then this will unroll twice and then stop.  If it hasn't then the unrolling won't terminate if you don't give an unrolling limit.
