### ISSUE TITLE
Please can someone who has access fix the codecov reports

### ISSUE THREAD

**Issue by martin-cs** [diffblue/cbmc#6247]
I tagged one regression test as needing the `smt-backend`.  codecov says:

```
Merging #6244 (9e32399) into develop (0002950) will increase coverage by 8.77%.
```

https://github.com/diffblue/cbmc/pull/6244#issuecomment-884550320

This is clearly nonsense.  Please can someone fix it?  Or, if that is not possible, can it at least not be a blocking part of the CI?

**Comment by NlightNFotis** [comment]
Last time I ported CI jobs, there were two (semi-competing) codecov jobs, submitting to reports to the same endpoint, which would create the effect of seeing one report come out fast and then changing to a more accurate one after an hour or something, when the second one was submitted.

After I ported the codecov job, I made sure to kill the two scripts submitting reports, and now we only have one. It seems for the most part to be doing its job, but then sometimes it fails spectacularly. I'm not really sure what causes that (the intermittent wild reports that is) - [the build process seems fine](https://github.com/diffblue/cbmc/blob/develop/.github/workflows/pull-request-checks.yaml#L662), we are building CBMC with coverage metrics and run `lcov` to collect it and submit it.

> This is clearly nonsense. Please can someone fix it? Or, if that is not possible, can it at least not be a blocking part of the CI?

Fixing this will require some digging into the depths of CI logs to see what's really going on when it fails to produce accurate metrics, which is probably going to take a rather uncomfortable amount of time for any results to materialise. 

As for it being blocking, I think it's specifically **not** marked as `REQUIRED`, exactly because it's so flaky. It doesn't block anything from getting merged, it just reports the CI run as failed if either of the two reports come out with decreased coverage (which is annoying, but not blocking merges).

Thoughts?

**Comment by martin-cs** [comment]
When it works it is really really valuable so I am in favour of keeping it.  The problem is that given a report, there is no way to tell whether it is accurate / complete.  I don't have the access or the time to fix it.  I would love it if someone else did.  Often I find with this kind of thing, it is worth spending a small amount of time to have an initial look and to work out what would need to be done to isolate the problem.  The run I highlighted should be an example of when it goes wrong.

**Comment by tautschnig** [comment]
I have just run into codecov report oddities again, and am guessing the following must be avoided:
- Pushing a branch that is not rebased against the latest develop. In such cases, Codecov might end up comparing apples and oranges.
- Pushing a fully rebased branch shortly after a merge to develop took place. In this case, Codecov for _develop_ hasn't caught up yet, and you once again apples and oranges are compared.

Besides these, the only issues I have witnessed in recent months can be explained by problems in floating-point precision (+/- 0.01 difference reported when nothing that has coverage measured even changed).

**Comment by tautschnig** [comment]
Closing given the explanation provided previously.
