### ISSUE TITLE
Windows error, cannot find the file specified.

### ISSUE THREAD

**Issue by Tutter** [diffblue/cbmc#6309]
I am having trouble getting cbmc to open and process files. I have tried giving the absoule path for the files, but I keep getting the same error. I have tried with different files and without all the options as well, but still I get the same error. I have included the console input and output below:

cbmc C:\Users\xx\CBMC-b00t-c0d3-main\mask_rom.c C:\Users\xx\CBMC-b00t-c0d3-main\mock_hmac.c memory_compare.c --function PROOF_HARNESS --unwind 97 --unwindset cmp_key.0:390 --unwindset cmp_image_len.0:5 --unwindset cmp_image_code.0:3 --unwindset cmp_modulus.0:385 --unwindset cmp_signature.0:385 --unwindset cmp_has_decrypt.0:33 --unwindset mask_rom_boot.0:2 --unwindset PROOF_HARNESS.0:2 --unwinding-assertions --pointer-check --bounds-check --object-bits 9

CBMC version 5.37.0 (cbmc-5.37.0) 64-bit x86_64 windows
Parsing C:\Users\tutta\Downloads\CBMC-b00t-c0d3-main\mask_rom.c
The system cannot find the file specified.   
CL Preprocessing failed
PARSING ERROR

**Comment by NlightNFotis** [comment]
Hello, the error message as I understand it indicates that the path to the file `C:\Users\tutta\Downloads\CBMC-b00t-c0d3-main\mask_rom.c` is wrong (or that at least CBMC cannot find a file at the specified path).

Can you double check that and let us know if the problem persists?

**Comment by Tutter** [comment]
I can confirm that the path is correct. I have also tried to open other files but I get the same error in all cases.

**Comment by NlightNFotis** [comment]
Hm, I did some digging up around the codebase, and I can see that the message you're observing (`The system cannot find the file specified.`) is the outcome of failed IPC on windows in case that a binary we're trying to run doesn't exist.

I speculate that this is because CBMC cannot find `cl` somewhere on the path. Going backwards from the error message, I can see that the most likely generator for it is CBMC trying to spawn a process of `cl` for preprocessing the C file, and then it fails for some reason. 

Can you verify if visual studio and the associated tools (`cl` primarily) are installed and accessible from the `PATH`?

**Comment by Tutter** [comment]
The issue was resolved by using the terminal through Visual Studio instead of a generic one. Thank you for your help.
