### ISSUE TITLE
Naming scheme for cbmc related tools

### ISSUE THREAD

**Issue by danielsn** [diffblue/cbmc#6440]
We have (and are developing more) open-source CBMC related tools.  We want to make sure there is a consistent naming scheme for these tools, and that our names for these tools make sense to the community.

In particular:

* https://github.com/awslabs/aws-viewer-for-cbmc makes formated (html and otherwise) reports from CBMC results. We would like to release it as a python package `cbmc-viewer`.
* https://github.com/model-checking/rmc/tree/main/compiler/cbmc is a set of rust bindings for CBMC data structures. Following the Rust convention, we would like to release it as a crate `cbmc`, much like the `z3` crate for z3 bindings https://crates.io/crates/z3
* We would like to add a trace viewer to VSCode, under a name to be determined.

**Comment by peterschrammel** [comment]
There aren't any general rules as far as I'm aware of.

Maybe some guidelines can be derived from these observations of current naming:
1. Anything that operates on intermediate representation is called `goto-`_what-it-is-doing_.
2. A BMC tool using a particular language frontend is called _language_`bmc`. Similar for static _language_`analyzer`, etc.
3. Packages that relate to the entire CProver infrastructure - rather than CBMC only - should have `cprover` in their name rather than `cbmc`.

I'd say that naming proposals should consider these, but individual naming decisions need to be made on a case per case basis.
- `cbmc-viewer` sound good to me if it is for CBMC only and cannot be used for JBMC and RMC; otherwise rule 3 should probably be considered. `cbmc-results-viewer` or `cbmc-trace-viewer` might be alternatives that are a bit lengthy for my taste, though.
- `rust-cprover-bindings` could be a possible name for accessing CProver data structures from Rust (following the scheme of `java-cprover-api` which serves a different purpose, though, namely exposing the __CPROVER_x functions for use in Java harnesses).
- `vscode-cbmc-trace-viewer` is a bit long. `vscode-cbmc-viewer` sounds better to me (going well with `cbmc-viewer` above).

**Comment by martin-cs** [comment]
@danielsn Thanks for asking!  Basically +1 to what @peterschrammel says.  There is no official naming scheme but the guide he gives are good and match with my understanding.

**Comment by danielsn** [comment]
@peterschrammel So the repo for the bindings would be `rust-cprover-bindings` and the Rust crate would be `cprover-bindings` since the (rust) part is implicit for a crate.

**Comment by danielsn** [comment]
@markrtuttle

**Comment by tautschnig** [comment]
Closing as question has been answered (confirmed by @danielsn).
