### ISSUE TITLE
Conversion error in goto-cc in develop branch

### ISSUE THREAD

**Issue by markrtuttle** [diffblue/cbmc#6530]
I'm getting a goto-cc conversion error on Ubuntu20 with develop branch commit 47c1c7e70cb17e3315ebacde99ef5b1f4a69eb91 that does not occur with release 5.44.

```
git clone https://github.com/FreeRTOS/corePKCS11
cd corePKCS11
git submodule update --init --checkout --recursive
cd test/cbmc/proofs/https://github.com/FreeRTOS/xInitializePkcs11Token
make goto
```

The root of the problem is that 
```
goto-cc  --export-file-local-symbols -fPIC -std=gnu90 -DMBEDTLS_CONFIG_FILE="<mbedtls_config.h>"  -I../../../../../corePKCS11/source/include -I../../../../../corePKCS11/test/cbmc/include -I../../../../../corePKCS11/source/dependency/3rdparty/pkcs11 -DCBMC=1 -DCBMC_OBJECT_BITS=8 -DCBMC_MAX_OBJECT_SIZE="(SIZE_MAX>>(CBMC_OBJECT_BITS+1))" ../../../../../corePKCS11/test/cbmc/proofs/xInitializePkcs11Token/xInitializePkcs11Token_harness.c ../../../../../corePKCS11/test/cbmc/stubs/pkcs11_interface_stubs.c -o ../../../../../corePKCS11/test/cbmc/proofs/xInitializePkcs11Token/gotos/proof1.goto
```
is failing with 
```
../../../../../corePKCS11/test/cbmc/stubs/pkcs11_interface_stubs.c: In function 'C_GetFunctionList':
../../../../../corePKCS11/test/cbmc/stubs/pkcs11_interface_stubs.c:63:1: error: expected constant expression, but got '{ .version={ .major=2, .minor=40 }, .$pad1=0, .C_Initialize=nondet_bool() == 0 ? ((CK_RV (*)(CK_VOID_PTR))NULL) : C_Initialize,
[deleted]
```

**Comment by tautschnig** [comment]
Posting in here after some out-of-band communication: @NlightNFotis confirmed that 1a86739a3e12 is the commit that causes this change in behaviour. The problem here is that a `static` variable is initialised (https://github.com/FreeRTOS/corePKCS11/blob/main/test/cbmc/stubs/pkcs11_interface_stubs.c#L62) with what isn't considered a compile-time constant (there are multiple function calls in there). I'd see two options (with input from @markrtuttle  appreciated):
1) Heap-allocate this object, doing a `malloc` first and then assigning this value.
2) The C front-end translating calls to `nondet...()` to `ID_nondet_symbol` plus `is_constantt` considering `ID_nondet_symbol` a constant.

**Comment by kroening** [comment]
I would be somewhat worried about option 2.

**Comment by tautschnig** [comment]
Thanks everyone for their input (several out-of-band). The conclusion is that changes will be made to the code under analysis, i.e., option 1 from the above. Closing this issue.
