### ISSUE TITLE
CBMC front-end support on vector in C++ STL 

### ISSUE THREAD

**Issue by sepideha** [diffblue/cbmc#6735]
CBMC version: `cbmc-5.52.0`
Operating system: `64-bit x86_64 MAC OS`
Exact command line resulting in the issue: `./cbmc  ex1-vec-satabs.cpp`
What behaviour did you expect: reporting a counterexample when the iterator `it` is dereferenced in the inappropriate place. 
What happened instead: `PARSING ERROR`

This is an example from SATABS webpage http://www.cprover.org/stl/ :

```
#include <vector>
using namespace std;
int main()
{
  vector<int>::iterator it;
  {
     vector<int> vec;
     vec.push_back(0);
     it = vec.begin();
  }
  *it = 1;   // undefined behavior
}
```
It seems SATABS was reporting a concrete counterexample due to violating an assertion in the header file vector associated with dereferencing iterator "it" in the last line. Is there a way to get the same result in CBMC?

[ex1-vec-satabs.log](https://github.com/diffblue/cbmc/files/8289622/ex1-vec-satabs.log)

**Comment by tautschnig** [comment]
I'm afraid that the C++ front-end will require work to support modern C++ (C++11 and later).

**Comment by martin-cs** [comment]
Hi Sepideh,

There are going to be a few problems getting that code to work...

1. The examples and web page are from around 2006 and quite a bit has changed in both CPROVER and C++.
2. The C++ front-end only handles basic uses of templates.  @peterschrammel was the last person to work on this I think but that may have been in 2017 or 2018?  I would guess it would handle maybe C++98 or C++03 level of templates. Modern STL implementations use a *lot* of template meta-programming and so the C++ doesn't handle them.  Using an alternative or older version of STL or writing a custom one (like the link) might work.
3. Here is my answer for the once a year that someone asks about SATABS:
< quote >
The last version I have was built on CBMC 4.7 which was released in Jan 2014. As far as I know that was a case of light maintainence and the last time it had active development was probably pre-2012.

I am not aware of any currently available copies of the source code.  I have a check out of the subversion from late 2015 and I can send you that / post it on github if you would like.  I don't know which version that is and it may take a non-trivial amount of work to get it to build / work with more modern versions of CPROVER.
< /quote >

Since then I have spoken with @tautschnig  and I think he has the last official copy of it but that is from 2015, maybe 2016?


< the your-asked-an-academic-a-question-so-you-get-extra-unsolicited-information section >
SATABS was great ... when it worked.  The problem was it was very, very dependent on picking the right predicates.  If it got them it could prove completeness fairly easily, if it didn't it would diverge pretty quickly.

The system for picking them was heuristic and ad-hoc at best and there was never a particularly good solution to how to do it.  Maybe with improved expression synthesis, maybe it would be worth another look.

In the academic community the response was to move to interpolation-based algorithms : IC3/PDR for hardware and IMPACT for software.  The idea was that expressions generated by the interpolant would be useful and relevant in a way that predicate abstraction struggled to be.

There were two interpolation-based tools written by the group at Oxford.  Wolverine in around 2011 and IMPARA in around 2016.  I don't think either are maintained.  The key problem is that bit-level interpolation works great, so IC3/PDR is really really good for hardware.  But word-level interpolation, esp. for bit-vectors just ... doesn't really work so well.  So it seems like software verification algorithms might be moving on from that as well.
< /the your-asked-an-academic-a-question-so-you-get-extra-unsolicited-information section >


If you wanted to get this working then I am sure people would love that and do their best to support but it is a fairly serious amount of work.  Depending on what you are trying to do, there may be easier approaches.

HTH

**Comment by sepideha** [comment]
Thanks @tautschnig for the clarification. And @martin-cs thank you for sharing the useful info and insightful comments.

< Just-out-of-curiosity > 
I'd like to get a clear picture about the "serious amount of work" that you mentioned:
Is there particular challenges or research questions on encoding C++ template instantiation in CBMC? Do templates need a special treatment different than the typical CPROVER workflow?

**Comment by tautschnig** [comment]
> Thanks @tautschnig for the clarification. And @martin-cs thank you for sharing the useful info and insightful comments.
> 
> < Just-out-of-curiosity > I'd like to get a clear picture about the "serious amount of work" that you mentioned: Is there particular challenges or research questions on encoding C++ template instantiation in CBMC? Do templates need a special treatment different than the typical CPROVER workflow?

There just were a lot of new language features added with C++11, see https://gcc.gnu.org/projects/cxx-status.html#cxx11 for a list. Very little of that would end up in the eventual goto program, but if we can't parse the code in the first instance we never get to that point. The item I last recall working on were variadic templates.

I'd say it takes a couple of week of very focussed work to determine how long it actually takes to really do the complete work.

**Comment by martin-cs** [comment]
@sepideha : to add to what @tautschnig has said.  There is not really an obvious research challenge as much of it is "compile time".  There is a lot of detailed engineering work and apart from STL and Boost it is not so clear that it will be used.  Most C++ codebases develop their own C++ subsets and these often avoid a lot of template magic.  Alternative approaches would be using the clang front-end like ESBMC does or an LLVM front-end.

However even if you get to the point where you can parse the STL and have it as a goto program, it is not clear that is a desirable state of affairs.  For example if the target code includes a `std::map` do you really want to be reasoning about a balanced tree implementation every time they look something up or would you rather model things using SMT uninterpreted functions or arrays?

If someone was paying me to support C++ (because I am not sure I would do that for free), I think I might take an approach like the one you originally linked and write a minimal / partial "verification friendly" STL implementation rather than try to parse "real" ones.

HTH

**Comment by sepideha** [comment]
Thanks for the comprehensive reply. Very useful!

**Comment by thomasspriggs** [comment]
> Thanks for the comprehensive reply. Very useful!

If you are happy with the comprehensive reply about the (lack) of C++ support, are you ok with us closing out this github issue?

**Comment by sepideha** [comment]
> 

Yes, sure! Feel free to close this issue, but we will look forward to see the C++ front-end support in CBMC :)
