### ISSUE TITLE
Ubuntu 20.04 package for CBMC 5.53.0 is missing

### ISSUE THREAD

**Issue by zhassan-aws** [diffblue/cbmc#6737]
The list of assets for CBMC 5.53.0 is missing the Ubuntu 20.04 deb package:

![image](https://user-images.githubusercontent.com/88045115/159038750-a03395f3-378b-4d03-a5b0-d184369f4ea4.png)

Previous versions typically included it:

![image](https://user-images.githubusercontent.com/88045115/159038868-762c6aee-0b95-43ab-92cc-1c188c64b7dc.png)

Was the Ubuntu 20.04 package intentionally dropped?

**Comment by ronakfof** [comment]
Seems like It's creation was failed in CI
https://github.com/diffblue/cbmc/actions/runs/2003407028

**Comment by NlightNFotis** [comment]
Hello,

Thanks for bringing this to our attention. There's a PR to fix this in https://github.com/diffblue/cbmc/pull/6738.

Because of the nature of CI changes, especially with regards to release scripts, this is going to take some time to fix, but estimate that we should land a fix in by early next week. In any case, it will require a minor version release, `5.53.1` to test the fix (and also provide binaries all platforms, assuming it works).

In the meantime, is it possible to continue using `5.52.0` binaries for that specific platform (Ubuntu 20.04), or build locally if version parity is required?

Apologies for any inconvenience caused.

**Comment by zhassan-aws** [comment]
Thanks. Yes, will continue to use 5.52.0 in the meantime.

**Comment by NlightNFotis** [comment]
Hello, taking the liberty to close this issue, given that we just released version `5.53.1`, and it appears that binaries for Ubuntu 20.04 are now present.

https://github.com/diffblue/cbmc/releases/tag/cbmc-5.53.1

I would like to thank you for bringing the issue to our attention and apologise again for any inconvenience caused.
