### ISSUE TITLE
`__CPROVER_same_object` returns true for pointers out of bounds

### ISSUE THREAD

**Issue by adpaco-aws** [diffblue/cbmc#6822]
In this program (let's call it `same.c`):
```c
#include <assert.h>

int main() {
    char *p1 = malloc(5);
    char *p2 = p1;
    assert(__CPROVER_same_object(p1, p2));
    p2 = p1 + 30;
    assert(__CPROVER_same_object(p1, p2));
}
```
both assertions pass, but p2 is out of bounds. Is this behavior intended?

CBMC version: 5.55.0
Operating system: Ubuntu 20.04
Exact command line resulting in the issue: cbmc same.c
What behaviour did you expect: FAILURE in the second assertion
What happened instead: SUCCESS in the second assertion

**Comment by NlightNFotis** [comment]
Hello @adpaco-aws, yes, I believe this behaviour is expected.

The reason for this is how pointers are modelled inside of CBMC.

Any object is represented as a pair of two values:

* The *pointer object*, which is a unique ID for the object
* The *pointer offset*, which is a number that is relative to the start of the object (used in arrays, pointer arithmetic, etc).

The primitive `__CPROVER_same_object(p1, p2)` resolves to `__CPROVER_POINTER_OBJECT(p1) == __CPROVER_POINTER_OBJECT(p2)`, which is true, as `p1` gets the identifier of the object produced by malloc, and `p2` is effectively an alias to the same object.

I believe the check you're looking for is:

```c
assert(__CPROVER_POINTER_OFFSET(p1) == __CPROVER_POINTER_OFFSET(p2));
```

This is going to fail because the `pointer_offset` part of the pointer representation is different:

```
[main.assertion.3] line 9 assertion __CPROVER_POINTER_OFFSET(p1) == __CPROVER_POINTER_OFFSET(p2): FAILURE

[snip]

Trace for main.assertion.3:

State 25 file /tmp/offset.c function main line 4 thread 0
----------------------------------------------------
  malloc_size=5ul (00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000101)

State 48 function main thread 0
----------------------------------------------------
  p1=(char *)dynamic_object1 (?)

State 50 file /tmp/offset.c function main line 5 thread 0
----------------------------------------------------
  p2=(char *)dynamic_object1 (?)

State 51 file /tmp/offset.c function main line 7 thread 0
----------------------------------------------------
  p2=(char *)(dynamic_object1 + 30l) (?)

Violated property:
  file /tmp/offset.c function main line 9 thread 0
  assertion __CPROVER_POINTER_OFFSET(p1) == __CPROVER_POINTER_OFFSET(p2)
  !((signed long int)(signed long int)!(POINTER_OFFSET((const void *)p1) == POINTER_OFFSET((const void *)p2)) != 0l)
```

A bit more elaborate description on that is at [Modeling pointers](https://github.com/diffblue/cbmc/blob/develop/doc/cprover-manual/modeling-pointers.md)

Let me know if I can assist any further.

**Comment by adpaco-aws** [comment]
Thanks @NlightNFotis for the detailed explanation!

It's also clear to me that this should be the intended behavior after working on the implementation of a few offset-related intrinsics for Kani. It's normal for CBMC to determine that `p2` is an alias for `p1` even if the offset is out of bounds; more complex checks should be done with `pointer_offset` as you indicate.

Closing this issue as my question has been answered, thanks again!
