### ISSUE TITLE
No file or function name when reporting memory leak

### ISSUE THREAD

**Issue by feliperodri** [diffblue/cbmc#6974]
CBMC version: 5.57.0 (cbmc-5.57.0)
Operating system: macOS Monterey 12.3.1
Exact command line resulting in the issue: 
1. Download/clone the branch [reproduce-error-memory-leak-report](https://github.com/feliperodri/s2n/tree/reproduce-error-memory-leak-report);
2. Enter directory `s2n/tests/cbmc/proofs/s2n_array_free`
3. Run `make`
4. Open HTML report in `s2n/tests/cbmc/proofs/s2n_array_free/report/html/index.html`.

What behavior did you expect: A proper file name and function indicating where the dynamic object leaked comes from. That might be tricky given the way we check for it. Is there a way we could improve this error message?

What happened instead:
![image (1)](https://user-images.githubusercontent.com/4294522/176019027-8e2d8e4e-8864-47a1-8488-a2bc2bca9169.png)

**Comment by feliperodri** [comment]
cc. @markrtuttle

**Comment by tautschnig** [comment]
@SaswatPadhi provided a nice idea in #6073 that would make for a more informative trace, although it would still not produce the actual source of the allocation.

**Comment by SaswatPadhi** [comment]
It's been a while since I looked at memory leak traces, but when I was last looking at it, the object id was being reported. As @tautschnig said above, it doesn't point to the source line for the allocation, but it's possible to figure that out by scrolling up in the trace.

For instance, in the example I reported in #6073 if we add a `leaked` at the end, then it points to the object (`dynamic_object2`) that was leaked:

```
State 105 file /Users/saspadhi/new-test.c function main line 6 thread 0
----------------------------------------------------
  leaked=(const void *)dynamic_object2 (00000011 00000000 00000000 00000000 00000000 00000000 00000000 00000000)
```

Further up in the trace, you would notice that `dynamic_object2` was created for the `*p2 = malloc(2)` call.

**Comment by feliperodri** [comment]
@tautschnig @SaswatPadhi Shall we close this issue and keep the #6073 open with this feature request?

**Comment by SaswatPadhi** [comment]
I believe we can, unless we want that bug report to be about automatically adding a `leaked` variable at the end of the main function, and this bug report to be about something more -- somehow presenting the source location for the allocation pointed to by `leaked`.

**Comment by feliperodri** [comment]
Already tracked at https://github.com/diffblue/cbmc/issues/6073
