### ISSUE TITLE
Feature request: Update CBMC homebrew tap with every release

### ISSUE THREAD

**Issue by zhassan-aws** [diffblue/cbmc#7031]
Thanks for providing CBMC's [homebrew tap](https://github.com/diffblue/homebrew-cbmc)! This is now [integrated in Kani's CI](https://github.com/model-checking/kani/blob/a06136b9425affb870b5c63f300eab66b7b2f467/scripts/setup/macos-10.15/install_cbmc.sh#L17), and allows us to pin a specific CBMC version for both Ubuntu and Mac.

This might already be in the works, but is it possible to update the homebrew tap as part of the CBMC release process? It seems that the update is currently performed manually because the latest CBMC release is 5.62.0, but the tap only has up to 5.61.0.

**Comment by NlightNFotis** [comment]
Hi @zhassan-aws, the tap should now contain `5.62.0` as well.

There was a small delay this release, primarily related to https://github.com/diffblue/cbmc/issues/7027 causing some issues with the action running the homebrew release, which got us a bit delayed. This should not be the case moving forward, as the runner for the PR has been moved to `macOS-11` as part of https://github.com/diffblue/cbmc/pull/7028.

Aside from this release being thrown a bit because of the runner issue, our usual policy is to perform a release every second Thursday, and then on the next day update the tap with the latest formula and the binaries.

The reason for the slight delay of the update of the tap is that we need to make sure that homebrew does have the latest release in before we can upgrade the tap, because we reuse the binaries that homebrew builds as part of a release to provide the tap binaries.

---

Without taking this release into account, and focusing on the usual process, is this something you can work with, or do you need us to have a deeper look into that?

**Comment by tedinski** [comment]
I think that's fine. Kani releases every 2 weeks on Tuesdays, so we're usually trying to turn around the Thursday release of cbmc into the Kani release 5 days later. We can do this just fine on Monday, but it'd be nice if we could reliably do it on Friday.

Is the Friday update of the tap reasonably automated? As long as we aren't at risk of regularly discovering the tap accidentally wasn't updated, I think we're good.

**Comment by NlightNFotis** [comment]
Hi @tedinski,

The release process right now is *semi-automated* (semi- because of branch permissions not allowing us to programmatically make changes to files, so we need one of us to submit a PR with a version change to the config file, make a tag out of the merged PR, and the rest of it is automated). There's some documentation on how it works [here](https://github.com/diffblue/cbmc/blob/develop/doc/ADR/release_process.md) if that's more helpful.

The tap is more recent, and as such the infrastructure to automate this hasn't been built yet - there's some to that effect, but nothing programmatic.

This hasn't been a problem up until now, given that I have allocated a calendar event to do just that every next day after the release, and the process is a 5 minute job (just run a `brew` command, a shell script, and commit).

I could work towards automating this further if that's a priority for you, but be advised that problems like what happened this release wouldn't be solved by automation, because this release we were blocked by a runner failing, and this would happen in the automated case as well, with a potential side-effect being that the discovery of the failure might be delayed.

**Comment by jimgrundy** [comment]
Closing. Let's see if the process in place now works.
