### ISSUE TITLE
Equivalence checking for Java-C or C-C

### ISSUE THREAD

**Issue by piyush-J** [diffblue/cbmc#7039]
I just started working on equivalence checking of programming languages, and I was wondering if CBMC/JBMC could be used to support equivalence checking of two C programs or Java-C programs? Or is there any other equivalence checking tool out there that uses JBMC/CBMC? 

Any guidance in this regard would be really helpful for me! 

Thanks in advance!

**Comment by NlightNFotis** [comment]
Hello, can you elaborate a bit on the meaning of

> equivalence checking of programming languages

in this context?

CBMC/JBMC can be used to tell you if a program is concordant to the language's specification according to certain properties (and modulo some constraints/bugs).

If you were to have a simple translation of `.c` and `.java` file, that do more or less the same thing, then running it by `cbmc` or `jbmc` would only tell you that the programs as they are obey certain properties, but not that they are semantically equivalent.

---

From what I gather from your question, you mean to compare the semantics as described by the C and Java language specifications directly? If that's the case, I suspect CBMC is not the best tool for that - you probably need to find a model of the operational semantics of the languages, and the memory models/abstract machine models of their equivalent runtimes, and get a logic/constraint solver to tell you how similar they are.

**Comment by piyush-J** [comment]
> you mean to compare the semantics as described by the C and Java language specifications directly?

Yes, this is what I meant. 

> I suspect CBMC is not the best tool for that

I see, that's what I thought. Thank you so much for your prompt reply! Are you aware of any such tool by any chance?

**Comment by NlightNFotis** [comment]
> Are you aware of any such tool by any chance?

Hm, I think your best bet might be something like [PLT Redex](https://redex.racket-lang.org)

**Comment by martin-cs** [comment]
@piyush-J People have and do use CBMC to do whole program or whole function C-C equivalence.  Generally this is pretty simple in that you have a wrapper function that calls both, one after the other and then asserts that their outputs are equal.  You run CBMC on the wrapper and then (modulo the usual caveats about bounded verification) get any counter-examples to equivalence.  This works and Pasquale Malacaria did some really interesting work using this approach for finding information leakage.

Other things that might be of use / interest:
* John Regher's Alive2 https://blog.regehr.org/archives/1722 https://github.com/AliveToolkit/alive2 does something similar but with LLVM, with the goal of finding compiler bugs.  Like the approach above, this is bounded.
* CPROVER's `goto-diff` computes a syntactic diff between two goto programs. @peterschrammel is the expert on this.
* If you wanted to build a program equivalence tool, `goto-diff` would give you a reasonable template to start from and CPROVER has most of the components you need.
* Ofer Strichman et al. worked on an area called regression verification or differential verification, which is closely related to program equivalence but focusing on similar programs.  https://github.com/boogie-org/symdiff was their tool.  IIRC it could do unbounded verification but required loop invariants to do so.  It should be pretty easy to reconstruct that using CPROVER's contract engine.
* I have a feeling that @sepideha 's UpProver does something like differential verification.
* Somewhere I have some notes on trying to do unbounded program verification by aligning loops.  Drop me a line if that would be useful.


If you want to go the route @NlightNFotis suggests and compare the languages (rather than programs written in the languages) then something like the K-Framework might be of interest.

HTH

**Comment by peterschrammel** [comment]
> you have a wrapper function that calls both, one after the other and then asserts that their outputs are equal

This could also done for Java-C, maybe not fully out-of-the-box, though. After some name-wrangling with a goto-instrument pass, one could link together the goto-binaries for C, Java and the wrapper and then run CBMC to perform the verification.

**Comment by piyush-J** [comment]
Thank you so much for your replies! It is really useful! 

I will explore these options and come back if I have any additional queries. :)
