### ISSUE TITLE
Setting the main function name in C++ does not work

### ISSUE THREAD

**Issue by exokortex** [diffblue/cbmc#7057]
CBMC version: `CBMC version 5.62.0 (cbmc-5.62.0) 64-bit x86_64 linux`, (also tested on 5.30.0 with the same result)
Operating system: Ubuntu 22.04
Exact command line resulting in the issue: `cbmc --function mymain mytest.cpp`
What behaviour did you expect:

This should result in cmbc using the function `mymain` as an entrypoint.

Content of `mytest.cpp`:

```
#include <assert.h>
void mymain()
{
  assert(0);
}
```

What happened instead:

cbmc cannot find the function and prints the error message:

```
$ cbmc --function 'mymain' mytest.cpp  
CBMC version 5.62.0 (cbmc-5.62.0) 64-bit x86_64 linux
Parsing mytest.cpp
Converting
Type-checking mytest
Invalid User Input
Option: --function
Reason: couldn't find function with name 'mymain' in symbol table
```

Adding parenthesis to the function name results in a different error message:

```
$ cbmc --function 'mymain()' mytest.cpp
CBMC version 5.62.0 (cbmc-5.62.0) 64-bit x86_64 linux
Parsing mytest.cpp
Converting
Type-checking mytest
main symbol 'mymain()' not found
main symbol 'mymain()' not found
SUPPORT FUNCTION GENERATION ERROR
```

Both errors are triggered by cbmc trying to find the function name in different symbol tables that use different formats. Adding parameters like `--cpp11` has no effect. It seems like this bug has been introduced a while ago (version 5.30.0 also gives the same error).

**Comment by NlightNFotis** [comment]
Hello,

It seems you're using the C++ language frontend, which isn't maintained very well.

You might find better luck if you do the same thing against a `.c` file. I just tried that with your example code (but in a `.c` file) and it works.

**Comment by danielsn** [comment]
Does it work if you export the harness as `extern C`?

**Comment by tautschnig** [comment]
As @exokortex correctly noted, the issue is that we are doing lookups in two different ways: `ansi_c_entry_point` (which is also used for the C++ entry point) uses the base name (which is `mymain`). `generate_entry_point_for_function`, however, uses the fully qualified name (which is `mymain()`). We should not be doing lookups in two different ways, and also need to consider whether the C++ front-end generating symbols with exactly this difference between a base name and the fully qualified name is the right thing to do.
