### ISSUE TITLE
Loop unwinding creates undesirable aliases when SHARING is enabled

### ISSUE THREAD

**Issue by hflsmax** [diffblue/cbmc#7058]
CBMC version:5.62
Operating system:Ubuntu 20.04
Exact command line resulting in the issue:NA
What behaviour did you expect:see below
What happened instead:see below

I'm working on a project that uses CBMC to do analysis and source-to-source transformation. After loops are unwinded, `exprt` inside `instructiont` across iterations becomes aliases because SHARING is enabled. We still want SHARING as it improves performance. Can you advice on how to unwind the loops while making sure each copy of `exprt` is unique?

**Comment by hflsmax** [comment]
We solved the problem by calling `irep::write()` to avoid sharing.

**Comment by martin-cs** [comment]
Hi @hflsmax , glad to hear you got this sorted.  Calling `irept::write()` will indeed break sharing, although that is not it's intended purpose but it should solve the immediate problem.

However I am a little worried about why this was a problem at all.  There isn't a way of doing this explicitly because if `irept` is used roughly as designed you should never need to do this.  Sharing is supposed to be invisible to the code built on top, or, conversely, code that uses `irept` based data-structures should assume that structurally equivalent `irept`s might be shared, or not.  Unrolling is far from the only source of sharing. `merge_ireps` is used various places in the code.  Inlining will probably also do this.  Maybe function pointer elimination.  Rather than working around, it might be better to change your code so that sharing doesn't change what it does.

Maybe you could briefly outline what you are doing and how and maybe one of the developers can help point you towards utilities that might avoid the issues you are having with sharing?
