### ISSUE TITLE
Array assignments not working as expected

### ISSUE THREAD

**Issue by JonasKlamroth** [diffblue/cbmc#7093]
CBMC version: 5.65.0
Operating system: ubuntu 20.04
Exact command line resulting in the issue: cbmc Test.c
What behaviour did you expect: sucessful verification
What happened instead: assertion failure

Consider the following simple program Test.c:
```
int main(int argc, char* argv) {
    int* a;
    a = malloc(sizeof *a);
    if(1) {
        a = (int[]){0};
    } 
    //a = (int[]){0};
    assert(a[0] == 0);
    return 0;
  }   
```

I would expect that a verification with and without the commented line is equally successful. However when running cbmc and the program as shown above with the line commented out this results in an assertion violation. CBMC seems to treat a[0] to be able to take any value. Is this intended behaviour? And if so i would highly appreciate some help to understand it.

**Comment by tautschnig** [comment]
C standard (C11) 6.5.2.5: "The value of the compound literal is that of an unnamed object initialized by the initializer list. If the compound literal occurs outside the body of a function, the object has static storage duration; otherwise, it has automatic storage duration associated with the enclosing block." The array within the `if` statement goes out of scope, so you're accessing a non-existent object in your `assert` statement.
