### ISSUE TITLE
Definy semantics for `__CPROVER_is_fresh(ptr,0)`

### ISSUE THREAD

**Issue by feliperodri** [diffblue/cbmc#7190]
CBMC version: 5.67.0
Operating system: N/A

Today, __CPROVER_is_fresh fails with the message "pointer outside object bounds in POINTER_OBJECT(*elem)" when used as an assumption and  the size argument is (allowed to be) 0.

I believe that when is_fresh(p,0ul) is used in a require it should:

- return true
- set p to a non-NULL value that could have been obtained from p=malloc(0ul)

Setting aside the case where size is 0, when is_fresh(p,size) is used as an assumption it should set p to a non-NULL value that could be returned by malloc(size).

What about the case when size is 0? The malloc manual says that when size is 0 malloc may either

1. return NULL, or 
2. return non-NULL value that may not be dereferenced, but may be freed

Consistency with malloc then suggests that when is_fresh(p,0ul) is used an assumption it should behave as described above.

Experiments with CBMC malloc and free appear to confirm that malloc can return a non-NULL value when called with size 0,  and that this value can be freed without error.

What about the behavior of is_fresh(p,size) when used as an assertion? Again, setting aside the case when size is 0 for the moment, it should return true iff p is the result of a call to malloc(size) that did not return NULL. Consistent behavior with malloc suggests that when is_fresh(p,0) is used as an assertion it should return true for a non-NULL value of p that was produced by malloc(0ul). Experiments with CBMC show that this is already the case, which strengthens the case for having is_fresh behave as requested when used as an assumption so that the two behaviors are more self consistent.

Apart from being the consistent thing to do, the requirement that is_fresh(p,0ul) should return true when used as an assumption has practical value. Consider the following function:

```c
void zero(char *p, size_t s)
{
   for (size_t i = 0; i < s; ++i) {
     *(p+i) = 0;
   }
}
```

What should the precondition for this function be? I would rather say that it was (is_fesh(p,s)) than have to say that it was ((s == 0ul) || is_fresh(p,s)).

**Comment by jimgrundy** [comment]
I think we know what we want here, let's do it.

**Comment by remi-delmas-3000** [comment]
with the current implementation you can write something like this:

```c
#include <stdlib.h>

void foo(char *arr, size_t size)
__CPROVER_requires(size < __CPROVER_max_malloc_size && __CPROVER_is_fresh(arr, size))
__CPROVER_assigns(__CPROVER_object_from(arr))
__CPROVER_frees(arr)
__CPROVER_ensures(__CPROVER_was_freed(arr))
{
    // size can be zero but arr is always non-null
    assert(arr != NULL);
    if(size > 0)
    {
        arr[0] = 0;
    }
    // can always be freed
    free(arr);
}

int main() {
    char *arr;
    size_t size;
    foo(arr, size);
}
```

and verification succeeds:

```c
❯ goto-cc main.c
❯ goto-instrument --dfcc main --enforce-contract foo a.out b.out
❯ cbmc b.out --pointer-check --pointer-primitive-check --pointer-overflow-check
...
** 0 of 763 failed (1 iterations)
VERIFICATION SUCCESSFUL
```


However with this version of foo, the assertion is proved, but the dereference fails

```c
void foo(char *arr, size_t size)
__CPROVER_requires(size < __CPROVER_max_malloc_size && __CPROVER_is_fresh(arr, size))
{
    assert(arr != NULL);
    *arr;
}
```

This shows that when `__CPROVER_is_fresh(ptr, 0)` holds, `ptr` points to something equivalent to what `malloc(0)` would give you.

The extra requirement `size < __CPROVER_max_malloc_size` is needed to ensure that assignable ranges of bytes can be represented internally by the instrumentation without having offset bits overflow into object bits.

To go one step further, I thought of embedding `size < __CPROVER_max_malloc_size` in `__CPROVER_is_fresh` itself, i.e . When `__CPROVER_is_fresh(ptr, size)` holds, then `size < __CPROVER_max_malloc_size` holds and the pointer points to a distinct object of size `size`, but backtracked from it because I think having all preconditions explicit is better.

Do you think this satisfactory in the current state ?

**Comment by jimgrundy** [comment]
Yes. I think this is good. I expect the dereference in the 2nd one to fail when size is 0.
- I had sometimes thought is_fresh should also return true for NULL, which would require us to add another precondition that is "arr != NULL". This would be a closer analog between is_fresh and malloc. But, it might be a pain to add the "p != NULL" everywhere you use is_fresh, since that is probably the more common expectation.
- like @remi-delmas-3000 I had also contemplated adding size < __CPROVER_max_malloc_size to is_fresh. The motivation for this would be that 
- i) surely there can be no larger malloced regions, so I don't think this should hurt in any way
- ii) ideally I'd like max_malloc_size to go away one day when we move to a better memory model, so it would be nice to embed the memory model specific things into the memory primitives so that we just update the memory primitives for each memory model and the user code should "just work".
On balance, I'm probably in favor of folding the max_malloc_size check into is_fresh, but I accept that I've not thought about this as deeply as others.
