### ISSUE TITLE
Generalize  `a[i]`  to `__CPROVER_POINTER_OBJECT(a)` or  `__CPROVER_object_slice(&a[0], i)` when inferring loop assigns clauses automatically

### ISSUE THREAD

**Issue by feliperodri** [diffblue/cbmc#7209]
CBMC version: 5.67.0
Operating system: N/A

When no user-provided assigns clause is given for a loop, we infer one from the loop's instructions and an automatically inferred aliasing relation.

For a loop like this one:

```c
int a[N];
for(int i=0; i <N; i++)
{
  a[i] = 0;
}
```

The inferred clause is `__CPROVER_assigns(i, a[i])`, which is insufficient to pass verification. We would like instead to infer `__CPROVER_POINTER_OBJECT(a)` or even `__CPROVER_object_slice(&a[0], i)` if `i` starts from 0 and is monotonically increasing.

In general we should probably generalize any expression that depends on any other target of the inferred assigns clause, and ask the user to specify an assigns clause.

**Comment by qinheping** [comment]
Implemented in #7228.  
The widening strategy is better than `__CPROVER_assigns(i, a[i])`, but is still not perfect.  It over-approximate the assigns clauses so that additional invariant clauses might be required to specify that untouched elements in `a` keep unchanged.
Can we do better? If we have a more precise over-approximate `[l, u]` of the range of `i`, we can have a better assign clause `__CPROVER_object_upto(a[l], u-l)`. However, the range of `i` is not always consecutive, i.e., it can be all even number less than `N`. So, the most precise assigns clause require quantifier such as `forall(j, even(j) && 0 < j < N, a[j])`. To me, it is more like the tradeoff between 
1. complicated invariant clauses with quantifiers + simple assigns clauses; or
2. simple invariant clauses + complicated assigns clauses with quantifiers.
