### ISSUE TITLE
Unroll loops using original name when checking contracts with DFCC

### ISSUE THREAD

**Issue by feliperodri** [diffblue/cbmc#7351]
CBMC version: `5.69.1 (cbmc-5.59.0-676-gb4a4122dee)`
Operating system: N/A
Exact command line resulting in the issue:
First, clone my fork for [coreJSON](https://github.com/feliperodri/coreJSON/tree/JSON_validate-proof). Then, navigate to the proof located at `coreJSON/verification/cbmc/proofs/skipString/`. Finally, take a look at the following [Makefile](https://github.com/feliperodri/coreJSON/blob/f99e8288218edc253bc78bcd4b20ca9624df4b7b/verification/cbmc/proofs/skipString/Makefile#L13).
What behaviour did you expect:
```Makefile
UNWINDSET += skipString.0:$(CBMC_MAX_BUFSIZE)
```
What happened instead: To unroll loops, one needs to use a mangled name.
```Makefile
UNWINDSET += skipString_wrapped_for_contract_checking.0:$(CBMC_MAX_BUFSIZE)
```

**Comment by remi-delmas-3000** [comment]
Indeed contract instrumentation mangles the name of checked functions, so if the loop to unwind is in that function you need to use the mangled name. 

However, it would be simpler to unwind these loops before contract instrumentation.

In Makefile.common there are two distinct unwind sets`EARLY_UNWINDSET` which is handled using goto-instrument, and `UNWINDSET` which is handled by cbmc at analysis time. 

Currently `EARLY_UNWINDSET` is applied after contract instrumentation, we could move this step before contract instrumentation so that the function name is not mangled yet.

**Comment by tautschnig** [comment]
It seems to me that the discussion is now one about what https://github.com/model-checking/cbmc-starter-kit does?!

**Comment by feliperodri** [comment]
This problem has been solved by using `EARLY_UNWINDSET`, which unrolls the loop before contracts instrumentation.
