### ISSUE TITLE
Refactoring of the `optionst` class [rfc]

### ISSUE THREAD

**Issue by thomasspriggs** [diffblue/cbmc#7691]
There is currently a certain amount of attention to the `optionst` class within my team, due to the work we have been doing for the API. As I see it there are a number of short falls with the `optionst` class which I am interested in improving upon -

- Because it essentially uses strings as keys for key-value pairings these are subject to typographical errors which cannot be detected by the compiler.
- Because the `optionst` class is a free-form structure which does not define which options are stored in it, working out what options are stored in it requires searching the code base for usages of the options string keys.
- Related to the previous point because this is a free-form container working out which types to read from it requires finding the corresponding writes.
- Although we can pass const references to the `optionst` class there is not necessarily a well defined point at which the setting of the options is complete. This is due to the potential for mutable references to the class to still exist/be in scope after the setting of the options has been completed.

I would like to propose a builder pattern based replacement for `optionst`. This has a number of benefits -
 - This will enable each of the options in use to be defined at compile time and strongly typed rather than managed based on key-value pairs.
 - It also provides a well defined point at which the setting of the options is completed based on transitioning from the builder class being in scope to the build result being in scope.
 - It gives a centralised place where the options are defined. This gives a place where doxygen for these options can be written and where consumers of the API can refer without reference to the rest of the code base.

Please note that this refactoring effort would not be touching the somewhat similar `cmdlinet` class because this class is specific to the command line argument parsing and is not functionality which is shared with the library API. I am interested in feed back from this proposal as it potentially touches many areas of the code base and I wanted to check whether there were strong reasons to leave it alone, or particular considerations which should be taken into account for a replacement.

**Comment by tautschnig** [comment]
I agree that `optionst` could do with considerable improvement, and I'd be more than happy to take a look at any implementation proposals. My sole concern at this point: Is
> It gives a centralised place where the options are defined. This gives a place where doxygen for these options can be written and where consumers of the API can refer without reference to the rest of the code base.

a desirable feature? Wouldn't that mean that somewhere-in-the-code-base there is a centralised place for entirely unrelated things? Not that we don't already have that (`configt`, irep ids) - but can we perhaps find a way to avoid a single central place?

**Comment by thomasspriggs** [comment]
> I agree that `optionst` could do with considerable improvement, and I'd be more than happy to take a look at any implementation proposals. My sole concern at this point: Is
> 
> > It gives a centralised place where the options are defined. This gives a place where doxygen for these options can be written and where consumers of the API can refer without reference to the rest of the code base.
> 
> a desirable feature? Wouldn't that mean that somewhere-in-the-code-base there is a centralised place for entirely unrelated things? Not that we don't already have that (`configt`, irep ids) - but can we perhaps find a way to avoid a single central place?

I am not opposed to the idea of separate options structures for separate "modules" of functionality within the code base. I can see the advantage in avoiding a monolithic class which defines every option itself. Although I think a structure which contains the combined options might be useful for use cases such as the command line UI.

However, if we want to use the same options data structures exposed for use via the library API and for use internally, then there are certain features which I think the API use case requires. Namely that for the library API the options have to be defined in headers which are packaged with the static library and do not contain #includes of headers which are private / not packaged. It is for this reason that I would like to be able to keep the options data structures free of dependencies on either the producer or consumers of the options and keep the options defined in their own header file(s). The inverse dependency where the producer and consumer of the options depend on the options is expected.

**Comment by kroening** [comment]
I am with Michael on avoiding the "big central" options data structure. I'd be ok with per-module classes.

We have not used the builder pattern so far, and the benefit doesn't seem worth the cost of introducing an new idiom.

**Comment by esteffin** [comment]
The main goal for this RFC is to have a singular option system that is used both internally and by the API.

Benefits of this is that there is no need to duplicate the option data structure (as it is now).
Another benefit is that the default values are set clearly, instead of the current system where options default values are spread on the codebase.

This approach, however, requires the option system to be reachable from the internal CBMC components as well as to the API user. Specifically:

1. the option types in the headers cannot contain any field of type not available to the user,
2. the option-related headers should be installed in the user machine.

The easiest way to achieve such requirements is to have a module with all the options, dependencies only limited to header only types included into source files, and whose headers will be installed to the user machine.

It is possible to avoid the external module structure by placing the option system into `util` or other modules and individually installing the necessary headers (while avoiding installing the other internal ones). However the main reason for why the option module is on its own (wrt part of `util`) is to avoid putting other data types to `util` increasing even more its size and making it a dumping ground.
It will make easier to the build system to verify that no other non-user-facing types are accidentally used publicly or installed.

Note that the [PR-7691](https://github.com/diffblue/cbmc/issues/7691) is just a first step towards this goal that only moves the API options to the new module.
When agreed on the structure and implementation details the internal `optionst` will be superseded and the internal existing components will use the new system.

**Comment by peterschrammel** [comment]
> Although I think a structure which contains the combined options might be useful for use cases such as the command line UI.

Note that the split between `cmdlinet` and `optionst` is on purpose - because it allows you to configure the modules used by an executable without having to expose all options of that module on the commandline.

Conceptually, an API should not operate on `cmdlinet` level, but on `optionst` level. So, don't think as `optionst` to be a representation for commandline options, but as a configuration object for the modules that are called from the API.

Having a separation of options per module is a good idea, in principle. Also, having a mechanism to combine these options into a single API-level configuration object may be useful (as the user of the API likely doesn't care about the underlying modules).

**Comment by NlightNFotis** [comment]
I am in favour of the proposal as put forward here, especially with the end result being a more robust and strongly typed implementation than what we currently have.

I am also of the opinion that a general location with all of the options is going to be much more ergonomic for both the development and the usage of the C++ API (`libcprover-cpp/`) given the constraints that we have around exposing private (implementation) headers.

**Comment by thomasspriggs** [comment]
I am going to close this out, as I don't currently expect to have time to push this further.
