### ISSUE TITLE
CBMC 5.85 goto-cc fails when GCC 12.2.0 on PATH

### ISSUE THREAD

**Issue by rod-chapman** [diffblue/cbmc#7783]
Using CBMC 5.85 on macOS.
I also have GCC 12.2.0 on PATH.

Running goto-cc, I get:

goto-cc --function foo -I../../include -DCBMC -o x.goto x.c
/opt/gcc-12.2.0-aarch64/lib/gcc/aarch64-apple-darwin21/12.2.0/include/stddef.h:432:1: error: syntax error before '__float128'
   __float128 __max_align_f128 __attribute__((__aligned__(__alignof(__float128))));
PARSING ERROR

Is there a workaround for this?

**Comment by tautschnig** [comment]
I had to do some more patching for the Debian package: https://sources.debian.org/src/cbmc/5.84.0-9/debian/patches/float128/ -- but I think this will require a slightly different fix. Might be that we wrongly assume to be talking to Clang (for it's MacOS).

**Comment by rod-chapman** [comment]
I will see if I can reproduce this problem on Linux... hang on...

**Comment by NlightNFotis** [comment]
From eyeballing the particular error here, it seems that with GCC on the path, the headers that are being included when the preprocessor ran are the ones that are included with that particular GCC distribution (because you're including `stddef.h` which includes size definitions for various types, IIRC).

Given that this is a GCC-header, it's very likely it comes with GCC intrinsics inside, that our parser can't cope with. Fixing that may require changes to our parser, or a quick patch to hide any problematic definitions if they're not relevant to the code you're trying to verify.

Let us know if the issue persists on Linux, because if that's the case then I think it's much more likely we will need the changes to the parser.

**Comment by rod-chapman** [comment]
Seems fine on x86_64 AL2 using GCC 12.2.0 and CBMC, so does indeed looks a macOS-specific issue.

**Comment by NlightNFotis** [comment]
Thanks @rod-chapman , can I ask for another favour if it's easy?

Would it be possible to give us a diff of the two `stddef.h`, the one from the Linux system and the one from the `macOS` system?

If it's not easy don't worry about it, we'll try to go about this another way.

**Comment by rod-chapman** [comment]
Here you go - there appears to be a significant difference:
```
rodchap@f4d4889dcf6d ~ % diff stddef_x86.txt stddef_aarch64.txt 
430,432c430,431
<      architectures, but only on i386 is extra alignment needed for
<      __float128.  */
< #ifdef __i386__
---
>      architectures.  */
> #if defined(__i386__) || (__APPLE__ && __aarch64__)
[stddef_aarch64.txt](https://github.com/diffblue/cbmc/files/11895329/stddef_aarch64.txt)
[stddef_x86.txt](https://github.com/diffblue/cbmc/files/11895330/stddef_x86.txt)

```

**Comment by kroening** [comment]
We currently assume that we are dealing with clang when on the Mac -- it's not obvious to me how we could detect that we aren't without running `gcc`.

A simple fix would be to call `clang` instead of `gcc` on the Mac, which would ensure that we are getting clang, even when gcc is on the path.

**Comment by remi-delmas-3000** [comment]
Hi, after checking with @rod-chapman it seems like a one-off extraordinary situation due to using a locally installed gcc compiler, we do not expect to encounter this situation that often.

**Comment by feliperodri** [comment]
@remi-delmas-3000 @rod-chapman shall we close this issue?

**Comment by rod-chapman** [comment]
Yes... happy to close this.
