### ISSUE TITLE
Finite loop run can't be terminated?

### ISSUE THREAD

**Issue by JingwenWu09** [diffblue/cbmc#7813]
```
#include <assert.h>

struct list {
  struct list *n;
};

struct obj {
  int n;
  struct list l;
} _o;

struct list _l = {.n = &_o.l};

int main(int argc, char *argv[]) {

  struct obj *o = &_o;
  _o.l.n = &_l;
  int count = 0;
  
  while (&o->l != &_l) {
    count++;
    o = ((struct obj *)((const char *)(o->l.n) - (const char *)&((struct obj *)0)->l));
  }
  assert(count == 1);
  
  return 0;
}

```
In this case, the value of count is 1, which is verified in both gcc and clang. Why does cbmc keep running and seemingly unstoppable? Please help me to explain this situation, thanks.

CBMC version: 5.88.0
Operating system: Ubuntu 22.04,  MacOS
command line:
```
cbmc example.c
```

**Comment by peterschrammel** [comment]
How would CBMC know that the loop is finite?

CBMC proceeds in two phases:
1. Symbolic execution with some imprecise analysis: This generates the SMT formula and may sometimes figure out that the loop condition becomes false. If it doesn't then it just continues unwinding the loop until you run out of memory. To prevent this, you need to bound the loop yourself by adding `--unwind` options.
2. Once it has got a (finite) SMT formula it solves that formula with bit-precise precision, which will determine whether or not an assertion fails within the number of unwindings that the formula contains. When an assertion after the loop exit doesn't fail then you may want to understand whether this is due to the assertion being always true or due to the loop never terminating. Rerunning with the `--unwinding-assertions` option will tell you that.

**Comment by JingwenWu09** [comment]
My understanding is that when the unwind is set to a value greater than the number of loop executions and ```assert()``` is true, the result of the ```unwinding assertion``` is **SUCCESS**. So in this example, I use ```count``` to keep track of how many times the loop was executed, and I get ```count = 1``` in gcc and clang. Running ```cbmc <filename.c> --unwind n --unwinding-assertions```, the result shows that ```assert(count == 1)``` is **SUCCESS** only if ```n = 1 || n = 2```, but the ```unwinding assertion``` is always **FAILURE** regardless of the value of ```n```. Is my understanding of unwind and unwinding-assertions wrong? Or is there something wrong with cbmc's analysis of this example?

**Comment by thomasspriggs** [comment]
Your example invokes undefined behaviour according to the standard, as the expression `((struct obj *)0)->l` dereferences a null pointer. This can be shown if you run your example with `--unwind 10 --pointer-check`. In the face of undefined behaviour your reasoning about other behaviour, such as the number of times a loop is executed may not hold.

**Comment by NlightNFotis** [comment]
Closing this as I think that this is now finished - feel free to reopen this if you feel like the question hasn't been answered to your satisfaction.
