### ISSUE TITLE
[Question] Minimum requirements for running CBMC in windows

### ISSUE THREAD

**Issue by FlorianBarrau** [diffblue/cbmc#7833]
CBMC version: 5.82
Operating system: Windows

Hello
I would like to know what are the minimum requirements for using CBMC in windows as a CLI. 
I realized that for some specific version of MinGW (e.g. MinGW-64 vs MinGW or gcc installed from cygwin), we can have different behaviors when running analysis. Especially from their standard libs. 

What version of MinGW or gcc do you recommand to use for using CBMC with windows?

Thank you in advance

**Comment by NlightNFotis** [comment]
Well, it might certainly be possible to build using any of those host platforms, but the one that we support officially** is a build around Visual Studio and its associated toolchain.

The rest of the platform combinations are highly experimental, and *may* work, but we don't promise official support or maintenance for those.

**: By ***officially*** I mean we:

1. Build against the platform on CI: pull request checks, release packages, etc., and
2. Provide compilation instructions that we keep up to date in the [`compiling.md`](https://github.com/diffblue/cbmc/blob/develop/COMPILING.md#working-with-visual-studio-on-windows) compilation instructions file.

**Comment by FlorianBarrau** [comment]
Thank you for the answer, i'd like to make sure that we are talking about the same thing. Allow me to elaborate my question

I am talking about using the CBMC executable cbmc.exe provided by the .msi in windows in command line. As in Linux we would have a "git bash", or a "Powershell" on windows. 

As far as i understand,
1. The default frontend used by CBMC in Windows is [cl.exe](https://learn.microsoft.com/en-us/cpp/build/reference/compiler-options?view=msvc-170) related to Microsoft Visual Studio Default Compiler
2. If we want to use "gcc" as frontEnd in Windows, we need to install something similar as MinGW or Cygwin, to be able to run CBMC analysis using commands starting with `cbmc --gcc whatever.c` This part is highly experimental
3. There is a case where MVSC could be used with gcc as explained in [this link](https://code.visualstudio.com/docs/cpp/config-mingw)
For this specific case, it is also highly experimental since it is not the default MSVC compiler

Am I correct?

**Comment by thomasspriggs** [comment]
The CBMC executable `cbmc.exe` provided by the `.msi` is built using Visual Studio. By default it assumes that Visual Studio is available for pre-processing and that the C code under analysis is intended to be built using Visual Studio. As far as I know, we do not test either building cbmc itself with any other compiler on Windows, or running cbmc with any other pre-processor or standard libraries on Windows.

In theory building and using cbmc on Windows without Visual Studio should be achievable, given that we support building/using with `gcc` / `clang` on other operating systems. Unfortunately, in practice such a platform setup is untested and attempting to use it is likely to encounter (invalid) assumptions that "Windows = Visual Studio". This goes a little deeper than just which pre-processor is invoked due to all other the other platform specifics. This may include details such as -

- Which compiler intrinsic functions/definitions should be available?
- Are the POSIX headers available? If I remember correctly this would be no for VS or MinGW, but yes for Cygwin. This is an important consideration given that we model some aspects of some of the platform specific libraries.
- Is `windows.h` available?
- The size of types such as `int` or `long`.

To re-iterate - These other Windows based compilers / tool chains, might work based on previous work undertaken to try them out and to do the right (portable) thing within our codebase. I would expect to encounter issues with using them, due to the current lack of testing in CI.

**Comment by thomasspriggs** [comment]
I think we can currently answer the original question as - "We would not recommend using gcc or MinGW with cbmc on Windows. Visual Studio should be considered as a minimum requirement for a well tested Windows environment".

Please feel free to reopen this issue (or to open a new issue) if you have further questions.
